@Arya_SuperApp_WebApi_HostAddress = http://localhost:5272

POST {{Arya_SuperApp_WebApi_HostAddress}}/workitem/create-workitem
Content-Type: application/json

{
  "name": "Hello Thailand"
}

###

PATCH {{Arya_SuperApp_WebApi_HostAddress}}/workitem/update-workitem/019b013c-1054-7198-b8ec-af7c50feb99b
Content-Type: application/json

{
    "name": "Foo bar"
}

###

GET {{Arya_SuperApp_WebApi_HostAddress}}/workitem/list-workitem/10/0
Accept: application/json

###

GET {{Arya_SuperApp_WebApi_HostAddress}}/workitem/get-workitem/019b013c-1054-7198-b8ec-af7c50feb99b
Accept: application/json

###

DELETE {{Arya_SuperApp_WebApi_HostAddress}}/workitem/delete-workitem/019afe2d-30a9-70a7-b695-01e04632958d

###

PATCH {{Arya_SuperApp_WebApi_HostAddress}}/workitem/link-workitem/019b0bf4-95da-734c-978d-f36e680f5b1c/Parent/019b0bf5-133d-73ab-b2ff-3ceec3368745

###

GET  {{Arya_SuperApp_WebApi_HostAddress}}/workitem/get-links/019b0bf4-95da-734c-978d-f36e680f5b1c

###

DELETE {{Arya_SuperApp_WebApi_HostAddress}}/workitem/delete-link/05140080-13e0-44ee-8f63-49b6329671cd

